export const ENGLISH_GLOSSARY: Readonly<Record<string, string>> = Object.freeze({
  '设置': 'Settings',
  '通用设置': 'General',
  '模型': 'Models',
  '插件': 'Plugins',
  '插件配置': 'Plugin configuration',
  '关闭': 'Close',
  '保存': 'Save',
  '取消': 'Cancel',
  '确认': 'Confirm',
  '删除': 'Delete',
  '编辑': 'Edit',
  '新建': 'New',
  '搜索': 'Search',
  '重试': 'Retry',
  '刷新': 'Refresh',
  '复制': 'Copy',
  '已复制': 'Copied',
  '启用': 'Enabled',
  '禁用': 'Disabled',
  '语言': 'Language',
  '外观': 'Appearance',
  '浅色': 'Light',
  '深色': 'Dark',
  '跟随系统': 'System',
  '工作区': 'Workspace',
  '会话': 'Sessions',
  '新会话': 'New session',
  '历史记录': 'History',
  '加载中': 'Loading',
  '暂无数据': 'No data',
  '任务看板': 'Task board',
  '更多': 'More',
  '帮助': 'Help',
  '关于': 'About',
  '连接': 'Connect',
  '断开连接': 'Disconnect',
  '成功': 'Success',
  '失败': 'Failed',
  '警告': 'Warning',
})

export function isKnownStaticPhrase(text: string): boolean {
  return Object.hasOwn(ENGLISH_GLOSSARY, text)
}
